### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by acabal** [b-t-k/thornton-w-burgess_green-meadow-stories#1]
- `indent` class is not necessary. Not only do we never want to have a class just to add an appearance property without semantic meaning, the class can probably and replaced with `blockquote + p`; but, even then, we don't want that because the SE style is to remove indents following blockquotes. There was no consensus as to whether or not to indent subsequent paragraphs after blockquotes back in the day so we remove indents.

- Filenames: The filenames should be the URL-safe titles: https://standardebooks.org/manual/1.0.0/2-filesystem#2.2.4.4  The books are not actually called "Book 1" so we need to adjust the filenames. Remember to update the manifest and ToC and run `se build --check` when you're done.

- Since we're putting all the chapters into a single file, we should add `section[epub|type~="chapter"]{ break-after: page; }`

- Did you clear the cover art with me? I don't have an entry. Please send over PD proof.

- In the imprint, just link to the first set of page scans. We don't want the imprint becoming a kind of 2nd credits. That's what the colophon is for.

- Colophon: `<abbr class="name">` around W.

- Short description: Remove author name and author bio; we just want a one sentence summary of what the book is about, not about the author

- Long description: 2nd to last paragraph seems to be missing words at the beginning?

**Comment by b-t-k** [comment]
Imprint: did we want to remove the extra gutenberg links as well?

All done except for indent class.
